import type { Metadata } from "next";
import { Lato, Rubik } from "next/font/google";
import "./globals.css";

const fontRubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const fontLato = Lato({
  variable: "--font-lato",
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontRubik.variable} ${fontLato.variable} antialiased h-screen flex flex-col`}
      >
        <header>This is Header</header>
        <main className="flex-1">
          {children}
        </main>
        <footer>This is Footer</footer>
      </body>
    </html>
  );
}
